title: DHR Cute Pets 2020
author: Jolene Smith
email: jolene.smith@dhr.virginia.gov
description: >-
  And the winner is...Jonathan the Cat! This contest was a fundraiser for the 2020 Commonewalth of Virginia Campaign. DHR staff raised over $800 on the quest for the cutest agency pet!

social:
  twitter:
  facebook:
  instagram:
  github:
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
