title: DHR Cute Pets 2022
author: Jolene Smith
email: jolene.smith@dhr.virginia.gov
description: >-
  Voting is open to DHR staff from 10/17-10/28 at 4PM. Each vote = $1 pledged with no limits. Vote for many pets! Come back as often as you like! You will receive a summary of pledges at the end of the contest. You must be logged into your COV account to vote or see results.

social:
  twitter:
  facebook:
  instagram:
  github:
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
